export const endpoint = {
  auth: {
    account_setup: "/business/setup",
    invite_member: "/business/send-invite",
    decode_invite_token: "/business/decode-invite",
    accept_invite: "/business/accept-invite",
    ims_setup: "/ims/setup",
    me: "/auth/me",
    forgot_password: "/auth/forgot-password",
    valid_token: "/auth/validate-reset-token",
    reset_password: "/auth/reset-password",
  },
  data_source: {
    fingerprint_configuration: "/fingerprint/configuration",
  },
  incident_ticket: {
    create: "/incident-ticket",
    get: "/incident-ticket",
    get_postmortems: "/postmortems",
    getTicket: "/tickets",
    get_members: "/business/get_members",
    send_comment: "/incident-ticket/comment",
    get_incident_id: "/incident-ticket/generate-id",
    get_comment: "/incident-ticket/comment",
    get_messages: "/incident-ticket/message",
    analytics: "/incident-ticket/analytics",
    history: "/tickets/history",
    integrations: "/integrations",
    gitlab_projects: "/integrations/gitlab/projects",
    github_repos: "/integrations/github/repos",
    postmorterm: {
      five_why: "/incident-ticket/resolve/ai/five-whys",
      suggestion: "/incident-ticket/resolve/ai/suggestion",
      stakeholder: "/incident-ticket/resolve/ai/stakeholder",
      customer_kb: "/incident-ticket/resolve/customer-kb",
      resolve: "/incident-ticket/resolve",
      generatePDF: "/generate-pdf",
    },
  },
  api_key: {
    create: "/apikey/createapikey",
    get: "apikey/apikeys",
  },
  integration: {
    whatsapp: "/integrations/whatsapp/connect",
    sms: "/integrations/sms/connect",
    slack: "/integrations/slack/connect",
    slack_callback: "/integrations/slack/oauth/callback",
    googlemeet: "/integrations/google/meet/connect",
    googlemeet_callback: "/integrations/google/meet/oauth/callback",
    github: "/integrations/github/connect",
    github_callback: "/integrations/github/callbacks/github",
    gitlab: "/integrations/gitlab/connect",
    gitlab_callback: "/integrations/gitlab/callback",
  },
  plans: {
    get: "/pricing/plans",
    create_subscription: "/pricing/subscriptions",
    create_session: "/pricing/checkout/create-session",
    getUserSubscription: "/pricing/customers",
  },
  portal: {
    get_companies: "/customer/companies",
    register: "/customer/register",
    login: "/customer/login",
    create_incident: "/customer/create-incident",
    get_incident: "/customer/get-incident",
    get_incidents: "/customer/get-incidents",
  },
  contact_us: "/mocktest/contact-us",
  on_call: {
    assign_member: "/assign-member",
    get_all_assign: "/get-all-assign",
    get_assign: "/get-assign",
  },
  dashboard: {
    get_metrics: "/dashboard/metrics",
    get_analytics: "/dashboard/analytics",
  },
};
