import React from "react";
import {
  Building2,
  Users2,
  ShieldCheck,
  Boxes,
  Layers3,
  Cable,
  FileText,
  Clock,
  Workflow,
  Bell,
  Send,
  Activity,
  Sparkles,
  Database,
  Lock,
  ScrollText,
  CreditCard,
  Bot,
  BookOpen,
  KeyRound,
  ShieldHalf,
  Palette,
  BadgeCheck,
  GitCommitHorizontal,
  GitPullRequestArrow,
  FileCheck2,
  RefreshCw,
  Server,
  Cpu,
  Code2,
  LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  org: Building2,
  users: Users2,
  roles: ShieldCheck,
  services: Boxes,
  env: Layers3,
  integ: Cable,
  policy: FileText,
  sla: Clock,
  rules: Workflow,
  flow: Workflow,
  notif: Bell,
  delivery: Send,
  status: Activity,
  ai: Sparkles,
  data: Database,
  security: Lock,
  audit: ScrollText,
  billing: CreditCard,
  agents: Bot,
  playbook: BookOpen,
  apikey: KeyRound,
  auth: ShieldHalf,
  paint: Palette,
  quality: BadgeCheck,
  causal: GitCommitHorizontal,
  decision: GitPullRequestArrow,
  compliance: FileCheck2,
  automation: RefreshCw,
  asset: Server,
  system: Cpu,
  developer: Code2,
};

export function CatIcon({ name, size = 20, className }: { name: string; size?: number; className?: string }) {
  const Cmp = ICONS[name] ?? Boxes;
  return <Cmp size={size} className={className} />;
}
