"use client";
import React, { useState } from "react";
import {
  X, Clock, Calendar, CheckCircle2, AlertTriangle,
  Info, Plus, ChevronDown, Shield, Sparkles,
} from "lucide-react";
import { SiZoom, SiGooglemeet } from "react-icons/si";
import { BiLogoMicrosoftTeams } from "react-icons/bi";
import { IncidentDetailRecord } from "@/lib/incident/incident.types";

interface ExternalContact { name: string; email: string }
interface Props {
  incident: IncidentDetailRecord;
  onClose: () => void;
  onDeclare: (data: WarRoomFormData) => void;
}
interface WarRoomFormData {
  platform: string; startMode: "immediate" | "scheduled";
  scheduleDate?: string; scheduleZone?: string;
  slackChannel: string; escalationPolicy: string;
  managers: string[]; externalContacts: ExternalContact[];
}

const PLATFORMS = [
  {
    id: "teams", name: "Microsoft teams", badge: "Enterprise",
    icon: BiLogoMicrosoftTeams,
    iconColor: "text-blue-600 dark:text-blue-400",
    iconBg: "bg-blue-100 dark:bg-blue-500/10 border border-blue-200 dark:border-blue-500/20",
    desc: (id: string) => `Creates #warroom-${id.toLowerCase()} · meeting link autogenerated`,
    link: "https://teams.microsoft.com/1/meet/warroom-si45698-kx7r9p",
  },
  {
    id: "zoom", name: "Zoom", badge: "Pro",
    icon: SiZoom,
    iconColor: "text-sky-600 dark:text-sky-400",
    iconBg: "bg-sky-100 dark:bg-sky-500/10 border border-sky-200 dark:border-sky-500/20",
    desc: () => "Instant meeting room · passcode + waiting room applied",
    link: null,
  },
  {
    id: "meet", name: "Google meet", badge: "Workspace",
    icon: SiGooglemeet,
    iconColor: "text-emerald-600 dark:text-emerald-400",
    iconBg: "bg-emerald-100 dark:bg-emerald-500/10 border border-emerald-200 dark:border-emerald-500/20",
    desc: () => "Calendar invite sent automatically to all invitees",
    link: null,
  },
];

const AFFECTED_SERVICES = [
  { name: "checkout-api", status: "Degraded", color: "text-orange-600 dark:text-orange-400", bg: "bg-orange-50 dark:bg-orange-500/10 border border-orange-200 dark:border-orange-500/20" },
  { name: "payment-svc",  status: "Offline",  color: "text-red-600 dark:text-red-400",       bg: "bg-red-50 dark:bg-red-500/10 border border-red-200 dark:border-red-500/20"             },
  { name: "order-router", status: "Degraded", color: "text-orange-600 dark:text-orange-400", bg: "bg-orange-50 dark:bg-orange-500/10 border border-orange-200 dark:border-orange-500/20" },
  { name: "user-session", status: "Elevated", color: "text-yellow-700 dark:text-yellow-400", bg: "bg-yellow-50 dark:bg-yellow-500/10 border border-yellow-200 dark:border-yellow-500/20" },
];

const EZRA_BULLETS: { type: "check" | "warn" | "info"; text: string }[] = [
  { type: "check", text: "Playbook match confidence is high (94%). Ezra will auto-populate triage steps on War Room open." },
  { type: "warn",  text: "payment-svc is offline — Ezra recommends a circuit-breaker check as first step." },
  { type: "info",  text: "Similar incident SI-003841 resolved in 22 min. Root cause was a DB connection pool exhaustion." },
  { type: "info",  text: "Guardrails active: EAL-L2 requires human approval before any automated rollback is executed." },
];

// ── Shared tokens — light base, dark override ─────────────────────

// Modal background
const modalBg     = "bg-white dark:bg-zinc-950";
// Card / surface inside modal
const cardBg      = "bg-zinc-50 dark:bg-zinc-900/60 border border-zinc-200 dark:border-zinc-800";
// Input
const inputBase   = [
  "w-full border border-zinc-300 dark:border-zinc-700",
  "bg-white dark:bg-zinc-800/60",
  "text-zinc-900 dark:text-zinc-200",
  "placeholder:text-zinc-400 dark:placeholder:text-zinc-600",
  "focus:border-zinc-500 dark:focus:border-zinc-500",
  "outline-none transition-colors rounded-lg px-3 py-2.5 text-[13px]",
].join(" ");
// Body text
const bodyText    = "text-zinc-700 dark:text-zinc-300";
const mutedText   = "text-zinc-500 dark:text-zinc-400";
const headingText = "text-zinc-900 dark:text-zinc-100";
// Section label
const sLabel      = `text-[11px] font-semibold uppercase tracking-wider ${mutedText} mb-2 block`;
// Border
const divider     = "border-zinc-200 dark:border-zinc-800";

// ── Sub-components ────────────────────────────────────────────────

const SectionTitle = ({ children, required }: { children: React.ReactNode; required?: boolean }) => (
  <h3 className={`text-[15px] font-bold ${headingText} mb-4 flex items-center gap-1.5`}>
    {children}{required && <span className="text-red-500">•</span>}
  </h3>
);

const MetaBadge = ({ label, value, valueClass }: { label: string; value: string; valueClass?: string }) => (
  <div className={`flex-1 min-w-[100px] rounded-lg px-3 py-2.5 bg-zinc-100 dark:bg-zinc-800/60 border border-zinc-200 dark:border-zinc-700`}>
    <p className={`text-[10px] font-semibold uppercase tracking-wider ${mutedText} mb-1`}>{label}</p>
    <p className={`text-[13px] font-semibold ${valueClass ?? headingText}`}>{value}</p>
  </div>
);

const SelectField = ({ label, options, value, onChange }: { label: string; options: string[]; value: string; onChange: (v: string) => void }) => (
  <div className="flex-1">
    <label className={sLabel}>{label}</label>
    <div className="relative">
      <select value={value} onChange={e => onChange(e.target.value)} className={`${inputBase} appearance-none pr-8`}>
        {options.map(o => <option key={o}>{o}</option>)}
      </select>
      <ChevronDown size={13} className="absolute right-2.5 top-1/2 -translate-y-1/2 text-zinc-400 pointer-events-none" />
    </div>
  </div>
);

// ── Main ──────────────────────────────────────────────────────────

const DeclareWarRoom: React.FC<Props> = ({ incident, onClose, onDeclare }) => {
  const [platform,     setPlatform]     = useState("teams");
  const [startMode,    setStartMode]    = useState<"immediate" | "scheduled">("immediate");
  const [scheduleDate, setScheduleDate] = useState("04/24/24");
  const [scheduleZone, setScheduleZone] = useState("Europe/london BST");
  const [slackChannel, setSlackChannel] = useState("Incident Command");
  const [escalation,   setEscalation]   = useState("P1-Immediate execution");
  const [managers,     setManagers]     = useState<string[]>(["Uchenna Chinka"]);
  const [managerInput, setManagerInput] = useState("");
  const [contacts,     setContacts]     = useState<ExternalContact[]>([{ name: "Vendor Support", email: "support@vendor.io" }]);
  const [copied,       setCopied]       = useState(false);

  const ticketId       = incident?.ticketId     ?? "SI-245789";
  const severity       = incident?.severity     ?? "P1";
  const environment    = incident?.environment  ?? "Production";
  const elapsed        = incident?.elapsedLabel ?? "00:19:59";
  const blastRadius    = incident?.blastRadius  ?? "4 services";
  const automationLevel = 2;

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const addManager = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && managerInput.trim()) {
      setManagers(p => [...p, managerInput.trim()]);
      setManagerInput("");
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className={`relative w-full max-w-[600px] max-h-[95vh] overflow-y-auto rounded-2xl ${modalBg} border border-zinc-200 dark:border-zinc-800 shadow-xl`}>

        {/* Close */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 z-10 w-8 h-8 rounded-full bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 flex items-center justify-center text-zinc-500 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100 hover:bg-zinc-200 dark:hover:bg-zinc-700 transition-colors"
        >
          <X size={14} />
        </button>

        <div className="px-6 pt-6 pb-8 space-y-7">

          {/* ── Header ── */}
          <div>
            <div className="flex items-start justify-between mb-1 pr-8">
              <h2 className={`text-[20px] font-black ${headingText}`}>Declare War Room</h2>
              <span className={`text-[13px] font-mono ${mutedText} mt-1`}>{ticketId}</span>
            </div>
            <div className="flex items-center gap-1.5 mb-4">
              <span className="w-1.5 h-1.5 rounded-full bg-red-500" />
              <span className="text-[12px] font-semibold text-red-600 dark:text-red-400">Critical Incident Report</span>
            </div>
            <div className="flex gap-2 flex-wrap">
              <MetaBadge label="Severity"     value={`${severity} — Critical`} valueClass="text-red-600 dark:text-red-400" />
              <MetaBadge label="Environment"  value={environment} />
              <MetaBadge label="Time open"    value={elapsed}     valueClass="text-amber-600 dark:text-amber-400" />
              <MetaBadge label="Blast Radius" value={blastRadius} valueClass="text-orange-600 dark:text-orange-400" />
            </div>
          </div>

          {/* ── Communications ── */}
          <div>
            <SectionTitle>Communications</SectionTitle>
            <div className="flex items-center justify-between mb-3">
              <span className={`text-[12px] font-semibold ${bodyText}`}>Platform <span className="text-red-500">•</span></span>
              <span className={`text-[11px] ${mutedText}`}>One channel per War Room</span>
            </div>
            <div className="space-y-2">
              {PLATFORMS.map(p => {
                const Icon = p.icon;
                const active = platform === p.id;
                return (
                  <div
                    key={p.id}
                    onClick={() => setPlatform(p.id)}
                    className={`flex items-start gap-3 p-4 rounded-xl border cursor-pointer transition-all ${
                      active
                        ? "border-blue-400 dark:border-blue-500/40 bg-blue-50 dark:bg-blue-500/5"
                        : `border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900/40 hover:border-zinc-300 dark:hover:border-zinc-700 hover:bg-zinc-50 dark:hover:bg-zinc-900/60`
                    }`}
                  >
                    <div className={`w-9 h-9 rounded-lg ${p.iconBg} flex items-center justify-center shrink-0 mt-0.5`}>
                      <Icon size={18} className={p.iconColor} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-0.5">
                        <span className={`text-[13px] font-semibold ${headingText}`}>{p.name}</span>
                        <span className={`text-[10px] font-semibold border border-zinc-300 dark:border-zinc-600 ${mutedText} rounded px-1.5 py-0.5`}>{p.badge}</span>
                      </div>
                      <p className={`text-[12px] ${mutedText}`}>{p.desc(ticketId)}</p>
                      {active && p.link && (
                        <div className="flex items-center gap-2 mt-2">
                          <span className="text-[11px] font-mono text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-500/10 border border-blue-200 dark:border-blue-500/20 rounded px-2 py-1 truncate max-w-[260px]">
                            {p.link}
                          </span>
                          <button
                            onClick={e => { e.stopPropagation(); handleCopy(p.link!); }}
                            className={`text-[10px] font-semibold border border-zinc-300 dark:border-zinc-600 ${bodyText} rounded px-2 py-1 hover:bg-zinc-100 dark:hover:bg-zinc-700 transition-colors shrink-0`}
                          >
                            {copied ? "Copied!" : "Copy"}
                          </button>
                        </div>
                      )}
                    </div>
                    <div className={`w-4 h-4 rounded-full border-2 flex items-center justify-center shrink-0 mt-1 transition-colors ${
                      active ? "border-blue-500 bg-blue-500" : "border-zinc-300 dark:border-zinc-600"
                    }`}>
                      {active && <div className="w-1.5 h-1.5 rounded-full bg-white" />}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* ── War Room Start ── */}
          <div>
            <SectionTitle required>War Room Start</SectionTitle>
            <div className={`flex rounded-xl overflow-hidden border ${divider} mb-4`}>
              <button
                onClick={() => setStartMode("immediate")}
                className={`flex-1 flex items-center justify-center gap-2 py-3 text-[13px] font-semibold transition-colors ${
                  startMode === "immediate"
                    ? "bg-emerald-500 text-white"
                    : "bg-zinc-50 dark:bg-zinc-800/60 text-zinc-600 dark:text-zinc-400 hover:bg-zinc-100 dark:hover:bg-zinc-800"
                }`}
              >
                <Clock size={14} /> Start immediately
              </button>
              <button
                onClick={() => setStartMode("scheduled")}
                className={`flex-1 flex items-center justify-center gap-2 py-3 text-[13px] font-semibold transition-colors border-l ${divider} ${
                  startMode === "scheduled"
                    ? "bg-zinc-800 dark:bg-zinc-700 text-white"
                    : "bg-zinc-50 dark:bg-zinc-800/60 text-zinc-600 dark:text-zinc-400 hover:bg-zinc-100 dark:hover:bg-zinc-800"
                }`}
              >
                <Calendar size={14} /> Schedule
              </button>
            </div>

            {startMode === "immediate" && (
              <div className="flex items-start gap-3 px-4 py-3 rounded-xl border border-emerald-300 dark:border-emerald-500/30 bg-emerald-50 dark:bg-emerald-500/5 mb-4">
                <CheckCircle2 size={15} className="text-emerald-600 dark:text-emerald-400 shrink-0 mt-0.5" />
                <p className="text-[12px] text-emerald-800 dark:text-emerald-300 leading-relaxed">
                  War Room will be provisioned immediately upon declaration. All channels and invitees notified instantly.
                </p>
              </div>
            )}

            {startMode === "scheduled" && (
              <div className="mb-4 space-y-3">
                <div className="flex gap-3">
                  <div className="flex-1 relative">
                    <input
                      type="text"
                      value={scheduleDate}
                      onChange={e => setScheduleDate(e.target.value)}
                      placeholder="MM/DD/YY"
                      className={`${inputBase} pr-10`}
                    />
                    <Calendar size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-400 pointer-events-none" />
                  </div>
                  <div className="flex-1 relative">
                    <select
                      value={scheduleZone}
                      onChange={e => setScheduleZone(e.target.value)}
                      className={`${inputBase} appearance-none pr-8`}
                    >
                      {["Europe/london BST","UTC","America/New_York EST","America/Los_Angeles PST","Asia/Tokyo JST","Asia/Kolkata IST"].map(tz => (
                        <option key={tz}>{tz}</option>
                      ))}
                    </select>
                    <ChevronDown size={13} className="absolute right-2.5 top-1/2 -translate-y-1/2 text-zinc-400 pointer-events-none" />
                  </div>
                </div>
                <div className="flex items-center gap-2 text-[12px] text-zinc-500 dark:text-zinc-400">
                  <Clock size={13} className="shrink-0 text-zinc-400 dark:text-zinc-500" />
                  <span>Invites and notifications will be sent 10 minutes before scheduled start.</span>
                </div>
              </div>
            )}

            <div className="flex gap-3">
              <SelectField label="Slack Channel"     value={slackChannel} onChange={setSlackChannel} options={["Incident Command","#sre-oncall","#platform-alerts","#war-room"]} />
              <SelectField label="Escalation policy" value={escalation}   onChange={setEscalation}   options={["P1-Immediate execution","P2-Standard","Custom escalation"]} />
            </div>
          </div>

          {/* ── Impact Assessment ── */}
          <div>
            <SectionTitle required>Impact Assessment</SectionTitle>

            {/* EAL bar */}
            <div className="mb-4">
              <div className="flex items-center justify-between mb-2">
                <span className={`text-[12px] ${bodyText}`}>Effective Automation Level</span>
                <span className={`text-[12px] font-semibold ${headingText}`}>Current: L{automationLevel} — Supervised</span>
              </div>
              <div className="h-2 bg-zinc-200 dark:bg-zinc-800 rounded-full mb-1 overflow-hidden">
                <div
                  className="h-full rounded-full bg-gradient-to-r from-emerald-600 to-emerald-400"
                  style={{ width: `${(automationLevel / 4) * 100}%` }}
                />
              </div>
              <div className={`flex justify-between text-[10px] ${mutedText} px-0.5`}>
                {["L0","L1","L2","L3","L4"].map(l => <span key={l}>{l}</span>)}
              </div>
            </div>

            {/* Affected services */}
            <div className="mb-4">
              <p className={sLabel}>Affected services</p>
              <div className="flex flex-wrap gap-2">
                {AFFECTED_SERVICES.map(s => (
                  <div key={s.name} className={`rounded-lg px-3 py-2 ${s.bg}`}>
                    <p className={`text-[12px] font-semibold ${headingText}`}>{s.name}</p>
                    <p className={`text-[11px] font-semibold ${s.color}`}>{s.status}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Matched Playbook */}
            <div className="mb-4">
              <p className={sLabel}>Matched Playbook</p>
              <div className={`flex items-center gap-3 p-4 rounded-xl ${cardBg}`}>
                <div className="w-9 h-9 rounded-lg bg-blue-100 dark:bg-blue-500/10 border border-blue-200 dark:border-blue-500/20 flex items-center justify-center shrink-0">
                  <Shield size={16} className="text-blue-600 dark:text-blue-400" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-0.5">
                    <span className={`text-[13px] font-semibold ${headingText}`}>Payment Gateway Outage Response</span>
                    <span className={`text-[10px] border border-zinc-300 dark:border-zinc-600 ${mutedText} rounded px-1.5 py-0.5`}>Workspace</span>
                  </div>
                  <p className={`text-[11px] ${mutedText}`}>Est. 18 min · 12 steps · Rev. 4.2</p>
                </div>
                <div className="text-right shrink-0">
                  <span className="text-[11px] font-bold text-emerald-600 dark:text-emerald-400 border border-emerald-300 dark:border-emerald-500/30 bg-emerald-50 dark:bg-emerald-500/5 rounded px-2 py-1">
                    94% match
                  </span>
                  <div className="mt-1.5 w-16 h-1 bg-zinc-200 dark:bg-zinc-800 rounded-full overflow-hidden">
                    <div className="h-full bg-emerald-500 rounded-full" style={{ width: "94%" }} />
                  </div>
                </div>
              </div>
            </div>

            {/* Ezra Intelligence */}
            <div className={`rounded-xl ${cardBg} p-4`}>
              <div className="flex items-center gap-2 mb-3">
                <Sparkles size={14} className="text-emerald-600 dark:text-emerald-400" />
                <span className="text-[13px] font-bold text-emerald-600 dark:text-emerald-400">Ezra Intelligence</span>
                <span className={`text-[12px] ${mutedText}`}>Pre-declaration analysis</span>
              </div>
              <div className="space-y-2.5">
                {EZRA_BULLETS.map((b, i) => (
                  <div key={i} className="flex items-start gap-2.5">
                    {b.type === "check" && <CheckCircle2 size={13} className="text-emerald-600 dark:text-emerald-400 shrink-0 mt-0.5" />}
                    {b.type === "warn"  && <AlertTriangle size={13} className="text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />}
                    {b.type === "info"  && <Info size={13} className="text-sky-600 dark:text-sky-400 shrink-0 mt-0.5" />}
                    <p className={`text-[12px] ${bodyText} leading-relaxed`}>{b.text}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* ── Responders ── */}
          <div>
            <SectionTitle required>Responders</SectionTitle>

            <div className="mb-4">
              <p className={sLabel}>Invite Managers</p>
              <div className={`flex flex-wrap items-center gap-2 border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-900/60 rounded-xl px-3 py-2.5 focus-within:border-zinc-400 dark:focus-within:border-zinc-500 transition-colors min-h-[44px]`}>
                {managers.map(m => (
                  <span key={m} className="flex items-center gap-1.5 bg-zinc-100 dark:bg-zinc-700 border border-zinc-200 dark:border-zinc-600 text-zinc-800 dark:text-zinc-200 text-[12px] font-medium rounded-lg px-2.5 py-1">
                    {m}
                    <button onClick={() => setManagers(p => p.filter(x => x !== m))} className={`${mutedText} hover:text-zinc-900 dark:hover:text-zinc-100 transition-colors`}>
                      <X size={11} />
                    </button>
                  </span>
                ))}
                <input
                  type="text"
                  value={managerInput}
                  onChange={e => setManagerInput(e.target.value)}
                  onKeyDown={addManager}
                  placeholder="Search managers"
                  className={`flex-1 min-w-[120px] bg-transparent outline-none text-[13px] text-zinc-800 dark:text-zinc-200 placeholder:text-zinc-400 dark:placeholder:text-zinc-600`}
                />
              </div>
            </div>

            <div>
              <div className={`flex items-center gap-3 mb-2 text-[11px] font-semibold uppercase tracking-wider ${mutedText}`}>
                <span className="flex-1">External Contacts</span>
                <span className="flex-1">Email</span>
                <span className="w-8" />
              </div>
              <div className="space-y-2">
                {contacts.map((c, i) => (
                  <div key={i} className="flex items-center gap-2">
                    <input
                      value={c.name}
                      onChange={e => setContacts(p => p.map((x, j) => j === i ? { ...x, name: e.target.value } : x))}
                      placeholder="Contact name"
                      className={`flex-1 ${inputBase}`}
                    />
                    <div className="flex-1 relative">
                      <input
                        value={c.email}
                        onChange={e => setContacts(p => p.map((x, j) => j === i ? { ...x, email: e.target.value } : x))}
                        placeholder="email@domain.com"
                        className={`${inputBase} pr-8`}
                      />
                      <ChevronDown size={12} className="absolute right-2.5 top-1/2 -translate-y-1/2 text-zinc-400 pointer-events-none" />
                    </div>
                    <button
                      onClick={() => setContacts(p => p.filter((_, j) => j !== i))}
                      className="w-8 h-8 rounded-lg border border-red-200 dark:border-red-500/40 bg-red-50 dark:bg-red-500/10 flex items-center justify-center text-red-500 dark:text-red-400 hover:bg-red-100 dark:hover:bg-red-500/20 transition-colors shrink-0"
                    >
                      <X size={13} />
                    </button>
                  </div>
                ))}
              </div>
              <button
                onClick={() => setContacts(p => [...p, { name: "", email: "" }])}
                className={`mt-3 w-full flex items-center justify-center gap-2 py-3 rounded-xl border border-zinc-200 dark:border-zinc-700 text-[13px] font-semibold ${bodyText} hover:bg-zinc-50 dark:hover:bg-zinc-800 hover:border-zinc-300 dark:hover:border-zinc-600 transition-colors`}
              >
                Add External Contact <Plus size={14} />
              </button>
            </div>
          </div>

          {/* ── Governance ── */}
          <div className="flex items-start gap-3 px-4 py-3.5 rounded-xl border border-emerald-300 dark:border-emerald-500/30 bg-emerald-50 dark:bg-emerald-500/5">
            <CheckCircle2 size={15} className="text-emerald-600 dark:text-emerald-400 shrink-0 mt-0.5" />
            <p className={`text-[12px] ${bodyText} leading-relaxed`}>
              <span className={`font-bold ${headingText}`}>Scrubbe Governance enforced.</span> Logged to immutable audit trail under policy{" "}
              <span className={`font-bold ${headingText}`}>IRP-P1-CRIT</span>. All approvals and actions are non-repudiable.
            </p>
            <span className={`text-[10px] font-bold border border-zinc-300 dark:border-zinc-600 ${mutedText} rounded px-1.5 py-0.5 shrink-0 self-start`}>SOC-2</span>
          </div>

          {/* ── Warning ── */}
          <div className="flex items-start gap-3 px-4 py-3.5 rounded-xl border border-amber-300 dark:border-amber-500/30 bg-amber-50 dark:bg-amber-500/5">
            <AlertTriangle size={15} className="text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
            <p className={`text-[12px] ${bodyText} leading-relaxed`}>
              Declaring will provision a War Room channel, activate the selected comms platform, and notify all invitees. The matched playbook will be loaded into Ezra for assisted triage.{" "}
              <span className={`font-semibold ${headingText}`}>This action cannot be undone.</span>
            </p>
          </div>

          {/* ── Buttons ── */}
          <div className="flex gap-3 pt-1">
            <button
              onClick={onClose}
              className={`flex-1 py-3.5 rounded-xl border border-zinc-200 dark:border-zinc-700 text-[14px] font-bold text-zinc-700 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-800 hover:border-zinc-300 dark:hover:border-zinc-600 transition-colors`}
            >
              Cancel
            </button>
            <button
              onClick={() => onDeclare({ platform, startMode, scheduleDate: startMode === 'scheduled' ? scheduleDate : undefined, scheduleZone: startMode === 'scheduled' ? scheduleZone : undefined, slackChannel, escalationPolicy: escalation, managers, externalContacts: contacts })}
              className="flex-1 py-3.5 rounded-xl text-[14px] font-bold text-white bg-red-600 hover:bg-red-500 transition-colors"
            >
              Declare War room
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DeclareWarRoom;