"use client";
import React from "react";
import { REMEDIES } from "./evidenceExplorer.data";
import { displayFont, monoFont } from "./fonts";

const RemediationModal: React.FC<{ open: boolean; onClose: () => void; onApprove: () => void }> = ({ open, onClose, onApprove }) => {
  if (!open) return null;
  return (
    <div className="fixed inset-0 bg-[rgba(20,20,30,0.34)] backdrop-blur-[2px] z-[150] flex items-center justify-center p-6" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className="bg-white rounded-[14px] shadow-2xl w-full max-w-[540px] max-h-[88vh] overflow-auto">
        <div className="flex items-start justify-between gap-3 px-5 pt-[18px] pb-3.5 border-b border-[#F0EFEA]">
          <div>
            <h3 className={`${displayFont.className} text-[17px] font-semibold m-0`}>Remediation plan</h3>
            <p className="text-[12px] text-[#8A8A93] mt-1">Ranked actions for incident SI-7A42K91, generated by Ezra.</p>
          </div>
          <button onClick={onClose} className="w-[30px] h-[30px] border border-[#E7E6E0] bg-white rounded-[8px] flex items-center justify-center shrink-0 hover:bg-[#F6F6F3]">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-[15px] h-[15px]"><path d="M6 6l12 12M18 6L6 18" /></svg>
          </button>
        </div>
        <div className="px-5 py-4">
          {REMEDIES.map(([rank, title, desc, outcome, conf, p1]) => (
            <div key={rank} className={`rounded-[10px] p-[13px] mb-2.5 flex gap-3.5 ${p1 ? "border border-[#DCE0FF] bg-[#EEF0FF]" : "border border-[#E7E6E0]"}`}>
              <span className={`w-[30px] h-[30px] rounded-[8px] flex items-center justify-center shrink-0 ${monoFont.className} font-semibold text-[12px] ${p1 ? "bg-[#2540F2] text-white" : "bg-white border border-[#E7E6E0]"}`}>
                {rank}
              </span>
              <div className="flex-1 min-w-0">
                <h4 className="text-[13.5px] font-semibold m-0 mb-0.5">{title}</h4>
                <div className="text-[12px] text-[#52525B]">{desc}</div>
                <div className="flex gap-4 mt-1.5 text-[11.5px] text-[#52525B]">
                  <span>Outcome <b className={`${monoFont.className} text-[#15151A]`}>{outcome}</b></span>
                  <span>Confidence <b className={`${monoFont.className} text-[#15151A]`}>{conf}</b></span>
                </div>
              </div>
            </div>
          ))}
        </div>
        <div className="flex gap-2.5 justify-end px-5 py-3.5 border-t border-[#F0EFEA] sticky bottom-0 bg-white">
          <button onClick={onClose} className="h-8 px-3 rounded-[7px] border border-[#E7E6E0] bg-white text-[12.5px] font-medium hover:bg-[#F6F6F3]">Dismiss</button>
          <button onClick={onApprove} className="h-8 px-3 rounded-[7px] bg-[#2540F2] text-white text-[12.5px] font-medium flex items-center gap-1.5 hover:bg-[#1B30C4]">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.9} className="w-3.5 h-3.5"><path d="M5 12l5 5 9-11" /></svg>
            Approve rollback
          </button>
        </div>
      </div>
    </div>
  );
};

export default RemediationModal;
