"use client";

import React, { useState } from "react";
import { toast } from "sonner";
import { SiZoom, SiGooglemeet } from "react-icons/si";
import { BiLogoMicrosoftTeams } from "react-icons/bi";
import { Loader2, RefreshCw } from "lucide-react";
import { cn } from "@/lib/utils";
import { useCreateWarRoom, useProvisionWarRoom, type WarRoom } from "@/hooks/useWarRoom";

interface PlatformDef {
  id: "teams" | "zoom" | "meet";
  name: string;
  badge: string;
  Icon: React.ComponentType<{ size?: number; className?: string }>;
  iconColor: string;
  iconBg: string;
  desc: (channel: string) => string;
  previewLink: ((channel: string) => string) | null;
  providerKey: string;
}
const PLATFORMS: PlatformDef[] = [
  {
    id: "teams", name: "Microsoft teams", badge: "Enterprise", Icon: BiLogoMicrosoftTeams,
    iconColor: "text-IMSLightGreen", iconBg: "bg-white dark:bg-white/5 border border-zinc-200 dark:border-white/10",
    desc: (c) => `Creates #warroom-${c} · meeting link autogenerated`,
    previewLink: (c) => `https://teams.microsoft.com/l/meet/warroom-${c}`,
    providerKey: "teams",
  },
  {
    id: "zoom", name: "Zoom", badge: "Pro", Icon: SiZoom,
    iconColor: "text-blue-600 dark:text-blue-400", iconBg: "bg-blue-100 dark:bg-blue-500/10 border border-blue-200 dark:border-blue-500/20",
    desc: () => "Instant meeting room · passcode + waiting room applied",
    previewLink: null,
    providerKey: "zoom",
  },
  {
    id: "meet", name: "Google meet", badge: "Workspace", Icon: SiGooglemeet,
    iconColor: "text-IMSLightGreen", iconBg: "bg-IMSLightGreen/10 border border-IMSLightGreen/20",
    desc: () => "Calendar invite sent automatically to all invitees",
    previewLink: null,
    providerKey: "google",
  },
];

const STATE_BADGE: Record<string, string> = {
  REQUESTED: "bg-zinc-100 text-zinc-600 dark:bg-white/10 dark:text-zinc-300",
  PROVISIONING: "bg-amber-50 text-amber-700 dark:bg-amber-500/10 dark:text-amber-400",
  READY: "bg-IMSLightGreen/10 text-IMSLightGreen",
  DEGRADED: "bg-amber-50 text-amber-700 dark:bg-amber-500/10 dark:text-amber-400",
  ARCHIVING: "bg-zinc-100 text-zinc-500 dark:bg-white/10 dark:text-zinc-400",
  ARCHIVED: "bg-zinc-100 text-zinc-500 dark:bg-white/10 dark:text-zinc-400",
  FAILED: "bg-red-50 text-red-600 dark:bg-red-500/10 dark:text-red-400",
};

function platformFor(provider?: string) {
  return PLATFORMS.find((p) => p.providerKey === provider) ?? PLATFORMS[0];
}

export default function CommunicationsPanel({ incidentId, ticketId, priority, warRoom, onDeclared }: { incidentId?: string; ticketId?: string; priority?: string; warRoom: WarRoom | null; onDeclared: () => void }) {
  const [platform, setPlatform] = useState<PlatformDef["id"]>("teams");
  const [copied, setCopied] = useState(false);
  const { createWarRoom, loading: creating } = useCreateWarRoom();
  const { provision, loading: provisioning } = useProvisionWarRoom();

  const channel = (ticketId || incidentId || "incident").toLowerCase();

  function copy(text: string) {
    if (typeof navigator !== "undefined" && navigator.clipboard?.writeText) {
      navigator.clipboard.writeText(text).then(() => { setCopied(true); setTimeout(() => setCopied(false), 1500); });
    }
  }

  async function start() {
    const chosen = PLATFORMS.find((p) => p.id === platform)!;
    try {
      const created = await createWarRoom({ incidentId, provider: chosen.providerKey, reason: `War room declared for the live incident via ${chosen.name}.`, priority });
      if (created?.warRoomId) {
        await provision(created.warRoomId).catch(() => undefined);
      }
      toast.success("War room communications provisioned");
      onDeclared();
    } catch {
      toast.error("Couldn't provision the war room channel");
    }
  }

  async function retryProvision() {
    if (!warRoom) return;
    try {
      await provision(warRoom.id);
      toast.success("Re-provisioned");
      onDeclared();
    } catch {
      toast.error("Provisioning failed again");
    }
  }

  if (warRoom) {
    const p = platformFor(warRoom.provider);
    return (
      <div className="rounded-xl bg-white dark:bg-grayscrubbe-900 p-5 shadow-sm shadow-light">
        <h3 className="font-ibm text-[15px] font-bold">Communications</h3>
        <div className="mt-3 flex items-center gap-3">
          <span className={cn("flex h-10 w-10 shrink-0 items-center justify-center rounded-lg", p.iconBg)}><p.Icon size={19} className={p.iconColor} /></span>
          <span className="min-w-0 flex-1">
            <span className="flex items-center gap-2">
              <span className="text-[13px] font-bold">{p.name}</span>
              <span className={cn("inline-flex h-[19px] items-center rounded-full px-2 text-[10px] font-bold", STATE_BADGE[warRoom.state] ?? STATE_BADGE.REQUESTED)}>{warRoom.state === "PROVISIONING" ? <Loader2 size={10} className="mr-1 animate-spin" /> : null}{warRoom.state}</span>
            </span>
            {warRoom.meetingUrl ? (
              <span className="mt-1.5 flex items-center gap-1.5">
                <span className="truncate rounded-md border border-IMSLightGreen/25 bg-IMSLightGreen/5 px-2 py-1 font-mono text-[11px] text-IMSLightGreen">{warRoom.meetingUrl}</span>
                <button type="button" onClick={() => copy(warRoom.meetingUrl!)} className="shrink-0 rounded-md border border-zinc-300 dark:border-zinc-600 px-2.5 py-1 text-[11px] font-semibold hover:bg-zinc-50 dark:hover:bg-white/5">{copied ? "Copied!" : "Copy"}</button>
              </span>
            ) : warRoom.channelRef ? (
              <span className="mt-1 block font-mono text-[11px] text-zinc-400">{warRoom.channelRef}</span>
            ) : null}
          </span>
          {(warRoom.state === "FAILED" || warRoom.state === "DEGRADED") && (
            <button type="button" onClick={retryProvision} disabled={provisioning} className="inline-flex shrink-0 items-center gap-1.5 rounded-md border border-zinc-200 dark:border-white/15 px-2.5 py-1.5 text-[11.5px] font-semibold hover:bg-zinc-50 dark:hover:bg-white/5 disabled:opacity-60">
              {provisioning ? <Loader2 size={12} className="animate-spin" /> : <RefreshCw size={12} />} Retry
            </button>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="rounded-xl bg-white dark:bg-grayscrubbe-900 p-5 shadow-sm shadow-light">
      <h3 className="font-ibm text-[15px] font-bold">Communications</h3>
      <div className="mt-3.5 flex items-center justify-between">
        <span className="text-[12.5px] font-bold">Platform</span>
        <span className="text-[11px] text-zinc-400">One channel per war room</span>
      </div>
      <div className="mt-2.5 flex flex-col gap-2">
        {PLATFORMS.map((p) => {
          const active = platform === p.id;
          const link = p.previewLink ? p.previewLink(channel) : null;
          return (
            <div key={p.id} onClick={() => setPlatform(p.id)} role="button" tabIndex={0} onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") setPlatform(p.id); }} className={cn("cursor-pointer rounded-lg border p-3 text-left transition-colors", active ? "border-IMSLightGreen bg-IMSLightGreen/5" : "border-zinc-200 dark:border-white/10 hover:border-zinc-300 dark:hover:border-white/20")}>
              <div className="flex items-start gap-3">
                <span className={cn("flex h-10 w-10 shrink-0 items-center justify-center rounded-lg", p.iconBg)}><p.Icon size={19} className={p.iconColor} /></span>
                <span className="min-w-0 flex-1">
                  <span className="flex items-center gap-2">
                    <span className="text-[13px] font-bold">{p.name}</span>
                    <span className="rounded border border-zinc-300 dark:border-zinc-600 px-1.5 py-0.5 text-[10px] font-semibold text-zinc-500">{p.badge}</span>
                  </span>
                  <span className="mt-0.5 block text-[11.5px] text-zinc-400">{p.desc(channel)}</span>
                  {active && link && (
                    <span className="mt-2 flex items-center gap-2">
                      <span className="min-w-0 flex-1 truncate rounded-md border border-IMSLightGreen/30 bg-IMSLightGreen/5 px-2 py-1.5 font-mono text-[11px] text-IMSLightGreen">{link}</span>
                      <button type="button" onClick={(e) => { e.stopPropagation(); copy(link); }} className="shrink-0 rounded-md border border-zinc-300 dark:border-zinc-600 px-2.5 py-1.5 text-[11px] font-semibold hover:bg-zinc-50 dark:hover:bg-white/5">{copied ? "Copied!" : "Copy"}</button>
                    </span>
                  )}
                </span>
                <span className={cn("mt-1 flex h-4 w-4 shrink-0 items-center justify-center rounded-full border-2", active ? "border-IMSLightGreen bg-IMSLightGreen" : "border-zinc-300 dark:border-white/20")}>{active && <span className="h-1.5 w-1.5 rounded-full bg-white" />}</span>
              </div>
            </div>
          );
        })}
      </div>
      <button type="button" onClick={start} disabled={creating || provisioning} className="mt-4 inline-flex w-full items-center justify-center gap-1.5 rounded-lg bg-red-600 px-3 py-2.5 text-[13px] font-bold text-white hover:bg-red-500 disabled:opacity-60">
        {(creating || provisioning) ? <Loader2 size={13} className="animate-spin" /> : null}
        {creating ? "Creating…" : provisioning ? "Provisioning…" : "Declare War room"}
      </button>
    </div>
  );
}
